steps:
  # Install dependencies
  - name: 'node:20-alpine'
    id: 'install-dependencies'
    dir: gamgui-server
    entrypoint: npm
    args: ['ci']

  # Run tests
  - name: 'node:20-alpine'
    id: 'execute-tests'
    dir: gamgui-server
    entrypoint: npm
    args: ['test']

  # Run linting check
  - name: 'node:20-alpine'
    id: 'lint-check'
    dir: gamgui-server
    entrypoint: npm
    args: ['run', 'lint']

  # Verify Dockerfile builds correctly
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '--no-cache'
      - '--pull'
      - '-t'
      - 'gamgui-server:validate'
      - .
    dir: gamgui-server
    id: docker-build-validate

timeout: 1200s
options:
  logStreamingOption: STREAM_ON
  logging: CLOUD_LOGGING_ONLY
serviceAccount: 'projects/${PROJECT_ID}/serviceAccounts/gamgui-registry-cloud-builder@${PROJECT_ID}.iam.gserviceaccount.com'
