apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gamgui-server-sa-admin
  namespace: gamgui
subjects:
- kind: ServiceAccount
  name: gamgui-server-sa
  namespace: gamgui
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
